// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "./components/product/addNewProdBrandCateg"
import "./components/product/adminProducts"
import "./components/product/products"
import "./components/product/productsFilter"
import "./components/product/productShow"
import "./components/home/home"
import "./components/nav/nav"
import "controllers"
